{"name": "Sample Test: Failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 1) == 3", "trace": "@allure.title(\"Sample Test: Failure\")\n    def test_failure():\n>       assert 1 + 1 == 3  # This will fail\nE       assert (1 + 1) == 3\n\ntests\\test_sample.py:11: AssertionError"}, "start": 1744106933181, "stop": 1744106933181, "uuid": "8b6b7454-004f-4edd-b243-f29337d5ce17", "historyId": "1d6c17aff211fcf45c4ea6df72e29ae4", "testCaseId": "1d6c17aff211fcf45c4ea6df72e29ae4", "fullName": "tests.test_sample#test_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "RiteshS-lpt"}, {"name": "thread", "value": "27652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_sample"}]}